// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1677646120);
user_pref("browser.search.region", "KE");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.caldav.googleResync", 1678548186);
user_pref("calendar.list.sortOrder", "ec79272a-9959-4883-b677-7c70bf4c096d");
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.calendar-main-default", true);
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.calendar-main-in-composite", true);
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.disabled", true);
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.name", "Home");
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.type", "storage");
user_pref("calendar.registry.ec79272a-9959-4883-b677-7c70bf4c096d.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Nairobi");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1678615945);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20230131132728");
user_pref("extensions.lastAppVersion", "102.7.1");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"72b6c0ea-2057-4d6c-bfff-edcfb75014e8\",\"google@search.mozilla.org\":\"54ffc7cd-e3a8-4586-a440-0e99b461ec8d\",\"ddg@search.mozilla.org\":\"45acf9e6-3bb2-47f1-8724-0a723bf4ac50\",\"amazondotcom@search.mozilla.org\":\"899573cc-136a-4a16-b233-1158f5ca152b\",\"wikipedia@search.mozilla.org\":\"2f477dfe-92de-4ff4-b078-944edfa960bf\",\"bing@search.mozilla.org\":\"47943ece-4ba0-4834-b7b7-a58f072283db\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "40a6c653-177c-4ae4-82c3-55d3522bd11");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "f1ebbe79-c3d1-4b1b-aff8-b3ed62923b1d");
user_pref("toolkit.telemetry.previousBuildID", "20230131132728");
